import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const catalogPath = path.join(rootDir, "shared", "tracker-catalog.json");
const trackingParamsPath = path.join(rootDir, "shared", "tracking-params.json");
const rulesPath = path.join(rootDir, "rules", "rules.json");
const configPath = path.join(rootDir, "shared", "config.js");

const BLOCK_RULE_ID = 1;
const CLEAN_URL_RULE_ID = 1000;
const BLOCK_RESOURCE_TYPES = [
  "csp_report",
  "font",
  "image",
  "media",
  "object",
  "other",
  "ping",
  "script",
  "stylesheet",
  "sub_frame",
  "websocket",
  "webtransport",
  "xmlhttprequest"
];
const CATEGORY_ORDER = [
  "Analytics",
  "Ad tracking",
  "Social pixel",
  "Session replay",
  "Affiliate / attribution",
  "Email marketing"
];
const DISALLOWED_BROAD_DOMAINS = new Set([
  "ads.google.com",
  "amazon.com",
  "business-api.tiktok.com",
  "cloudflare.com",
  "facebook.com",
  "github.com",
  "google.com",
  "hubspot.com",
  "mailchimp.com",
  "microsoft.com",
  "paypal.com",
  "platform.twitter.com",
  "stripe.com",
  "youtube.com"
]);

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function writeJson(filePath, value) {
  fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`);
}

function normalizeDomain(domain) {
  return String(domain || "").trim().toLowerCase();
}

function assertValidCatalog(catalog) {
  const seen = new Set();

  for (const tracker of catalog.trackers || []) {
    const domain = normalizeDomain(tracker.domain);

    if (!domain || !tracker.category || !tracker.label) {
      throw new Error(`Invalid tracker catalog entry: ${JSON.stringify(tracker)}`);
    }

    if (DISALLOWED_BROAD_DOMAINS.has(domain)) {
      throw new Error(`Refusing broad high-breakage domain: ${domain}`);
    }

    if (seen.has(domain)) {
      throw new Error(`Duplicate tracker domain in catalog: ${domain}`);
    }

    seen.add(domain);
  }
}

function uniqueSorted(values) {
  return Array.from(new Set(values)).sort((a, b) => a.localeCompare(b));
}

function escapeRegex(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function buildRules(domains, trackingParams) {
  return [
    {
      id: BLOCK_RULE_ID,
      priority: 1,
      action: {
        type: "block"
      },
      condition: {
        requestDomains: domains,
        domainType: "thirdParty",
        resourceTypes: BLOCK_RESOURCE_TYPES
      }
    },
    {
      id: CLEAN_URL_RULE_ID,
      priority: 2,
      action: {
        type: "redirect",
        redirect: {
          transform: {
            queryTransform: {
              removeParams: trackingParams
            }
          }
        }
      },
      condition: {
        regexFilter: `[?&](${trackingParams.map(escapeRegex).join("|")})=`,
        resourceTypes: [
          "main_frame"
        ]
      }
    }
  ];
}

function buildCategories(trackers) {
  const categories = {};

  for (const category of CATEGORY_ORDER) {
    categories[category] = [];
  }

  for (const tracker of trackers) {
    const category = tracker.category;
    if (!categories[category]) {
      categories[category] = [];
    }

    categories[category].push(normalizeDomain(tracker.domain));
  }

  for (const [category, domains] of Object.entries(categories)) {
    categories[category] = uniqueSorted(domains);
  }

  return categories;
}

function buildConfig({ domains, categories, trackingParams }) {
  return `// Generated by scripts/generate-rules.mjs. Edit shared/tracker-catalog.json or shared/tracking-params.json instead.
(function exposeGetBlockedConfig(globalScope) {
  const TRACKING_PARAMS = ${JSON.stringify(trackingParams, null, 2)};

  const TRACKER_DOMAINS = ${JSON.stringify(domains, null, 2)};

  const TRACKER_CATEGORIES = ${JSON.stringify(categories, null, 2)};

  globalScope.GetBlockedConfig = Object.freeze({
    BLOCK_RULE_ID: ${BLOCK_RULE_ID},
    CLEAN_URL_RULE_ID: ${CLEAN_URL_RULE_ID},
    TRACKING_PARAMS,
    TRACKER_DOMAINS,
    TRACKER_CATEGORIES
  });
})(globalThis);
`;
}

const catalog = readJson(catalogPath);
const trackingParams = readJson(trackingParamsPath);
assertValidCatalog(catalog);

const trackers = catalog.trackers.map((tracker) => ({
  ...tracker,
  domain: normalizeDomain(tracker.domain)
}));
const domains = uniqueSorted(trackers.map((tracker) => tracker.domain));
const categories = buildCategories(trackers);
const rules = buildRules(domains, trackingParams);

writeJson(rulesPath, rules);
fs.writeFileSync(configPath, buildConfig({ domains, categories, trackingParams }));

console.log(`Generated ${rulesPath}`);
console.log(`Generated ${configPath}`);
console.log(`Tracker domains: ${domains.length}`);
